openapi: 3.0.3

info:
  title: Document Management API
  version: 1.0.0
  description: API for document upload and management

servers:
  - url: http://localhost:3000/api/v1

paths:
  $ref: "./paths/index.yaml"

components:
  schemas:
    $ref: "./schemas/index.yaml"